services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data
      - rabbitmq_logs:/var/log/rabbitmq # Persistent logs
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - testing_net

volumes:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24